// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"
	"encoding/json"
)

type Querier interface {
	Add(ctx context.Context, content json.RawMessage) (int64, error)
	Find(ctx context.Context, content json.RawMessage) (Message, error)
	List(ctx context.Context) ([]Message, error)
}

var _ Querier = (*Queries)(nil)
