// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package database

import (
	"context"
)

const add = `-- name: Add :one
INSERT INTO messages (content) VALUES ($1) RETURNING id
`

func (q *Queries) Add(ctx context.Context, content []byte) (int64, error) {
	row := q.db.QueryRow(ctx, add, content)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const find = `-- name: Find :one
SELECT id, content FROM messages WHERE content = ($1::jsonb)
`

func (q *Queries) Find(ctx context.Context, content []byte) (Message, error) {
	row := q.db.QueryRow(ctx, find, content)
	var i Message
	err := row.Scan(&i.ID, &i.Content)
	return i, err
}
