// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"
)

type Querier interface {
	Add(ctx context.Context, content []byte) (int64, error)
	Find(ctx context.Context, content []byte) (Message, error)
}

var _ Querier = (*Queries)(nil)
